// SPDX-License-Identifier: MIT
//
// Copyright 2025 bniladridas. All rights reserved.
// Use of this source code is governed by a MIT license that can be
// found in the LICENSE file.


// Mocks generated by Mockito 5.4.6 from annotations
// in browser/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_inappwebview/src/find_interaction/find_interaction_controller.dart'
    as _i3;
import 'package:flutter_inappwebview_platform_interface/flutter_inappwebview_platform_interface.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePlatformFindInteractionController_0 extends _i1.SmartFake
    implements _i2.PlatformFindInteractionController {
  _FakePlatformFindInteractionController_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FindInteractionController].
///
/// See the documentation for Mockito's code generation for more information.
class MockFindInteractionController extends _i1.Mock
    implements _i3.FindInteractionController {
  MockFindInteractionController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PlatformFindInteractionController get platform => (super.noSuchMethod(
        Invocation.getter(#platform),
        returnValue: _FakePlatformFindInteractionController_0(
          this,
          Invocation.getter(#platform),
        ),
      ) as _i2.PlatformFindInteractionController);

  @override
  _i4.Future<void> findAll({String? find}) => (super.noSuchMethod(
        Invocation.method(
          #findAll,
          [],
          {#find: find},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> findNext({bool? forward = true}) => (super.noSuchMethod(
        Invocation.method(
          #findNext,
          [],
          {#forward: forward},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearMatches() => (super.noSuchMethod(
        Invocation.method(
          #clearMatches,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setSearchText(String? searchText) => (super.noSuchMethod(
        Invocation.method(
          #setSearchText,
          [searchText],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getSearchText() => (super.noSuchMethod(
        Invocation.method(
          #getSearchText,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<bool?> isFindNavigatorVisible() => (super.noSuchMethod(
        Invocation.method(
          #isFindNavigatorVisible,
          [],
        ),
        returnValue: _i4.Future<bool?>.value(),
      ) as _i4.Future<bool?>);

  @override
  _i4.Future<void> updateResultCount() => (super.noSuchMethod(
        Invocation.method(
          #updateResultCount,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> presentFindNavigator() => (super.noSuchMethod(
        Invocation.method(
          #presentFindNavigator,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> dismissFindNavigator() => (super.noSuchMethod(
        Invocation.method(
          #dismissFindNavigator,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.FindSession?> getActiveFindSession() => (super.noSuchMethod(
        Invocation.method(
          #getActiveFindSession,
          [],
        ),
        returnValue: _i4.Future<_i2.FindSession?>.value(),
      ) as _i4.Future<_i2.FindSession?>);

  @override
  void dispose({bool? isKeepAlive = false}) => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
          {#isKeepAlive: isKeepAlive},
        ),
        returnValueForMissingStub: null,
      );
}
