---
# SPDX-License-Identifier: MIT
#
# Copyright 2025 bniladridas. All rights reserved.
# Use of this source code is governed by a MIT license that can be
# found in the LICENSE file.

name: 'Bump Version'
description: 'Bump version based on PR labels and create release'

inputs:
  pr-number:
    description: 'Pull request number'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Determine bump type
      id: bump-type
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |

        # Get PR title to check if it's a version bump PR
        PR_TITLE=$(gh pr view "${{ inputs.pr-number }}" --json title -q '.title')
        printf "PR Title: %s\n" "${PR_TITLE}"

        if printf "%s" "${PR_TITLE}" | grep -q "^chore: bump version to"; then
          printf "Skipping bump for version bump PR\n"
          printf "bump-type=skip\n" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Get PR labels
        LABELS=$(gh pr view "${{ inputs.pr-number }}" --json labels -q '.labels[].name')
        printf "Labels: %s\n" "${LABELS}"

        if printf "%s" "${LABELS}" | grep -q -x "major"; then
          BUMP_TYPE="major"
        elif printf "%s" "${LABELS}" | grep -q -x "minor"; then
          BUMP_TYPE="minor"
        elif printf "%s" "${LABELS}" | grep -q -x "patch"; then
          BUMP_TYPE="patch"
        else
          # Default to patch if no label
          BUMP_TYPE="patch"
        fi

        printf "bump-type=%s\n" "${BUMP_TYPE}" >> $GITHUB_OUTPUT

    - name: Bump version
      if: steps.bump-type.outputs.bump-type != 'skip'
      shell: bash
      run: |
        ./bump_version.sh ${{ steps.bump-type.outputs.bump-type }}

    - name: Get version
      id: version
      shell: bash
      run: |
        VERSION=$(cut -d'+' -f1 VERSION)
        echo "version=${VERSION}" >> $GITHUB_OUTPUT

    - name: Create version bump PR
      if: steps.bump-type.outputs.bump-type != 'skip'
      shell: bash
      run: |
        set -e

        VERSION=${{ steps.version.outputs.version }}
        BRANCH_NAME="version-bump-${VERSION}"
        # Check if PR already exists
        EXISTING_PR=$(gh pr list --head "$BRANCH_NAME" --base main --json number --jq 'length')
        if [ "$EXISTING_PR" -gt 0 ]; then
          echo "Version bump PR for $VERSION already exists. Skipping."
          exit 0
        fi
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git checkout -b "$BRANCH_NAME"
        git add VERSION pubspec.yaml
        git commit -m "chore: bump version to ${VERSION}"
        git push origin "$BRANCH_NAME"
        gh pr create --title "chore: bump version to ${VERSION}" --body "Automated version bump to ${VERSION} after merging PR ${{ inputs.pr-number }}." --base main --head "$BRANCH_NAME"

    - name: Create and push tag if it does not exist on remote
      if: steps.bump-type.outputs.bump-type == 'skip'
      shell: bash
      run: |
        VERSION=${{ steps.version.outputs.version }}
        if git ls-remote --tags --exit-code origin "desktop/app-${VERSION}"; then
          echo "Tag desktop/app-${VERSION} already exists on remote. Skipping tag creation."
        else
          git tag "desktop/app-${VERSION}"
          git push origin "desktop/app-${VERSION}"
        fi

    - name: Create release if not exists
      if: steps.bump-type.outputs.bump-type == 'skip'
      shell: bash
      run: |

        VERSION=${{ steps.version.outputs.version }}
        if gh release view "desktop/app-${VERSION}" &>/dev/null; then
          echo "Release for tag desktop/app-${VERSION} already exists. Skipping release creation."
        else
          PR_TITLE=$(gh pr view "${{ inputs.pr-number }}" --json title -q '.title')
          PR_BODY=$(gh pr view "${{ inputs.pr-number }}" --json body -q '.body' | head -20)
          NOTES=$(printf "## What's New in %s\n\n%s\n\n%s\n\n(auto bump)" \
            "${VERSION}" "${PR_TITLE}" "${PR_BODY}")
          gh release create "desktop/app-${VERSION}" --title "Release ${VERSION}" --notes "${NOTES}"
        fi
      env:
        GH_TOKEN: ${{ github.token }}
